// Automatically generated by astro-icon
// f226d2ec2477ae8c96f6afebcd7bc231c4f6e824b9ff2eca4c281479711feb5e

declare module 'virtual:astro-icon' {
	export type Icon = 
		| "heart-full"
		| "heart-outline";
}